<#
.SYNOPSIS
    Generates PciNames.C from the official pci.ids file.
.DESCRIPTION
    Parses the PCI ID database and produces static C tables + binary-search
    lookup functions for vendor and device names.
    source: https://pci-ids.ucw.cz/
.PARAMETER PciIdsPath
    Path to the pci.ids file (default: .\pci.ids)
.PARAMETER OutputDir
    Directory where the .C file will be written
.EXAMPLE
    .\Generate-PciNames.ps1
.EXAMPLE
    .\Generate-PciNames.ps1 -PciIdsPath "Shadow/BUS/PCI/pci.ids" -OutputDir "Shadow/BUS/PCI/"
#>

[CmdletBinding()]
param(
    [string]$PciIdsPath = ".\pci.ids",
    [string]$OutputDir  = "."
)

$ErrorActionPreference = "Stop"

trap {
    Write-Host "`n--- ERROR ---" -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor Red
    Write-Host $_.InvocationInfo.PositionMessage -ForegroundColor Yellow
    Write-Host $_.ScriptStackTrace -ForegroundColor Yellow
    break
}

if (-not (Test-Path -LiteralPath $PciIdsPath)) {
    Write-Error "pci.ids not found at '$PciIdsPath'"
}

if (-not (Test-Path -LiteralPath $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
}

Write-Host "Reading $PciIdsPath ..."
$lines = Get-Content -LiteralPath $PciIdsPath -Encoding UTF8

$vendors       = @{}          # int → @{ Name = string; Devices = ordered hashtable }
$currentVendor = $null
$vendorRx      = [regex]'^([0-9a-fA-F]{4})\s{2,}(.+)$'
$deviceRx      = [regex]'^\t([0-9a-fA-F]{4})\s{2,}(.+)$'

$lineNum = 0
foreach ($line in $lines) {
    $lineNum++
    $line = $line.TrimEnd("`r")

    if ([string]::IsNullOrWhiteSpace($line) -or $line.StartsWith("#")) { continue }
    if ($line.StartsWith("C ")) { break }
    # Vendor
    $m = $vendorRx.Match($line)
    if ($m.Success) {
        $vid  = [Convert]::ToInt32($m.Groups[1].Value, 16)
        $name = $m.Groups[2].Value.Trim()
        $vendors[$vid] = @{
            Name    = $name
            Devices = @{}
        }
        $currentVendor = $vid
        continue
    }

    # Device (only if we already have a current vendor)
    if ($null -ne $currentVendor) {
        $m = $deviceRx.Match($line)
        if ($m.Success) {
            $did  = [Convert]::ToInt32($m.Groups[1].Value, 16)
            $name = $m.Groups[2].Value.Trim()
            $vendors[$currentVendor].Devices[$did] = $name
            continue
        }
    }

    # Everything else (subsystem lines, comments we already skipped, etc.) is ignored
}

$vendorCount = $vendors.Count
$deviceCount = 0
foreach ($v in $vendors.Values) { $deviceCount += $v.Devices.Count }

Write-Host "Parsed $vendorCount vendors, $deviceCount devices"

if ($vendorCount -eq 0) {
    Write-Error "No vendors found – is the file a valid pci.ids?"
}

function Escape-CString([string]$s) {
    return $s.Replace('\', '\\').Replace('"', '\"')
}

$sourcePath = Join-Path $OutputDir "PciNames.C"
$sb = [System.Text.StringBuilder]::new(2MB)

[void]$sb.AppendLine(@"
/*
	* Shadow/BUS/PCI/PciNames.C - Auto-generated from pci.ids
	* Do not edit by hand.  Regenerated by Generate-PciNames.ps1
	* Copyright (c) 2026 OwlyNest
*/

/* --- Styling Instructions ---
	* Encoding:                      UTF-8, Unix line endings
	* Text font:                     Monospace
	* Line width:                    Max 80 characters
	* Indentation:                   Use 4 spaces
	* Brace style:                   Same line as control statement
	* Inline comments:               Column 40, wherever possible, else, whole multiple of 20
	* Section headers:               Use 3 '-' characters before and after
	* Pointer notation:              Next to variable name, not type
	* Binary operations:             Space around operator
	* Empty parameter list:          Use (VOID) instead of ()
	* Statements and declarations:   Max one per line
*/

/* --- Includes ---*/
#include <BUS/PCI/PCI.H>

/* --- Typedefs - Structs - Enums ---*/
typedef struct PciIdName {
    UINT16          Id;
    PCCHAR          Name;
} _PciIdName, *_PPciIdName;

typedef struct PciVendorEntry {
    UINT16                  Id;
    PCCHAR                  Name;
    const _PciIdName       *Devices;
    UINT16                  NumDevices;
} _PciVendorEntry, *_PPciVendorEntry;

/* --- Globals ---*/
"@)

# Device tables  (Dev_xxxx)
foreach ($vid in ($vendors.Keys | Sort-Object)) {
    $devs = $vendors[$vid].Devices
    if ($devs.Count -eq 0) { continue }

    $hex = $vid.ToString("x4")
    [void]$sb.AppendLine("static const _PciIdName Dev_$hex[] = {")
    foreach ($did in ($devs.Keys | Sort-Object)) {
        $name = Escape-CString $devs[$did]
        [void]$sb.AppendLine("    {0x$($did.ToString('x4')), `"$name`"},")
    }
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine()
}

# Vendor table
[void]$sb.AppendLine("static const _PciVendorEntry Vendors[] = {")
foreach ($vid in ($vendors.Keys | Sort-Object)) {
    $v    = $vendors[$vid]
    $name = Escape-CString $v.Name
    $hex  = $vid.ToString("x4")

    if ($v.Devices.Count -gt 0) {
        [void]$sb.AppendLine("    {0x$hex, `"$name`", Dev_$hex, $($v.Devices.Count)},")
    } else {
        [void]$sb.AppendLine("    {0x$hex, `"$name`", NULL, 0},")
    }
}
[void]$sb.AppendLine("};")
[void]$sb.AppendLine()
[void]$sb.AppendLine("static const SIZE_T NumVendors = $vendorCount;")
[void]$sb.AppendLine()

# Lookup functions (binary search) – house style
[void]$sb.AppendLine(@"
/* --- Functions ---*/

static PCCHAR BsearchName(
    const _PciIdName *Tbl,
    SIZE_T            N,
    UINT16            Id
) {
    SIZE_T Lo = 0;
    SIZE_T Hi = N;

    while (Lo < Hi) {
        SIZE_T Mid = Lo + (Hi - Lo) / 2;

        if (Tbl[Mid].Id < Id) {
            Lo = Mid + 1;
        } else {
            Hi = Mid;
        }
    }

    if (Lo < N && Tbl[Lo].Id == Id) {
        return Tbl[Lo].Name;
    }

    return NULL;
}

PCCHAR PciVendorName(
    UINT16 VendorId
) {
    SIZE_T Lo = 0;
    SIZE_T Hi = NumVendors;

    while (Lo < Hi) {
        SIZE_T Mid = Lo + (Hi - Lo) / 2;

        if (Vendors[Mid].Id < VendorId) {
            Lo = Mid + 1;
        } else {
            Hi = Mid;
        }
    }

    if (Lo < NumVendors && Vendors[Lo].Id == VendorId) {
        return Vendors[Lo].Name;
    }

    return NULL;
}

PCCHAR PciDeviceName(
    UINT16 VendorId,
    UINT16 DeviceId
) {
    SIZE_T Lo = 0;
    SIZE_T Hi = NumVendors;

    while (Lo < Hi) {
        SIZE_T Mid = Lo + (Hi - Lo) / 2;

        if (Vendors[Mid].Id < VendorId) {
            Lo = Mid + 1;
        } else {
            Hi = Mid;
        }
    }

    if (Lo >= NumVendors || Vendors[Lo].Id != VendorId) {
        return NULL;
    }

    if (Vendors[Lo].NumDevices == 0) {
        return NULL;
    }

    return BsearchName(Vendors[Lo].Devices, Vendors[Lo].NumDevices, DeviceId);
}
"@)

$sb.ToString() | Set-Content -LiteralPath $sourcePath -Encoding utf8
$sizeMB = [math]::Round((Get-Item -LiteralPath $sourcePath).Length / 1MB, 2)
Write-Host "Wrote $sourcePath ($sizeMB MB)"
Write-Host "Done."